# permissions for end users to view konfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konfiguration-viewer-role
rules:
- apiGroups:
  - apps.kubecfg.io
  resources:
  - konfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.kubecfg.io
  resources:
  - konfigurations/status
  verbs:
  - get
