# permissions for end users to edit konfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konfiguration-editor-role
rules:
- apiGroups:
  - apps.kubecfg.io
  resources:
  - konfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubecfg.io
  resources:
  - konfigurations/status
  verbs:
  - get
