apiVersion: jsonnet.io/v1beta1
kind: Konfiguration
metadata:
  name: konfiguration-sample
spec:
  interval: 30s
  prune: true
  path: https://github.com/pelotech/jsonnet-controller/raw/main/config/jsonnet/whoami.jsonnet
  variables:
    extStr:
      name: 'hello-world'
    # Code must be used for integers, booleans, and complex types.
    # Even though it is a string field, it is utilized as raw jsonnet
    # code.
    extCode:
      port: '8080'