apiVersion: jsonnet.io/v1beta1
kind: Konfiguration
metadata:
  name: konfiguration-sample
spec:
  interval: 30s
  prune: true
  path: https://github.com/pelotech/jsonnet-controller/raw/main/config/jsonnet/whoami-tla.jsonnet
  variables:
    tlaVars:
      name: hello-world
      port: 8080