apiVersion: jsonnet.io/v1beta1
kind: Konfiguration
metadata:
  name: whoami
spec:
  interval: 30s
  path: config/jsonnet/whoami.jsonnet
  prune: true
  variables:
    extStr:
      name: 'whoami'
    extCode:
      port: '8080'
  # inject: |
  #   {
  #     deployment+: { spec+: { replicas: 2 } },
  #   }
  sourceRef:
    kind: GitRepository
    name: jsonnet-samples
    namespace: flux-system