name: Build

on:
  create:
    tags:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Login to container reigstry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      if: ${{ github.event_name != 'pull_request' }}

    - name: Get image version
      shell: bash
      run: |
        echo ::set-output name=tag::$([[ "${GITHUB_REF##*/}" == "main" ]] && echo latest || echo ${GITHUB_REF##*/})
      id: version

    - name: Build the controller image
      run: VERSION=${{ steps.version.outputs.tag }} make docker-build

    - name: Push the controller image
      run: VERSION=${{ steps.version.outputs.tag }} make docker-push
      if: ${{ github.event_name != 'pull_request' }}

    - name: Force pkg.go.dev to refresh main
      run: curl "https://proxy.golang.org/github.com/pelotech/kubecfg-operator/@v/${GITHUB_REF##*/}.info"
      if: ${{ steps.version.outputs.tag == 'latest' && github.event_name != 'pull_request' }}

    - name: Force pkg.go.dev to refresh version
      run: curl https://proxy.golang.org/github.com/pelotech/kubecfg-operator/@v/${{ steps.version.outputs.tag }}.info
      if: ${{ steps.version.outputs.tag != 'latest' && github.event_name != 'pull_request' }}
