on:
  push:
    tags:
      - 'v*'

name: Konfig Release

jobs:
  release:
    name: Build and publish konfig binary
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Install upx
        run: sudo apt-get install -y upx

      - name: Build Release
        run: make dist-konfig

      - name: Publish Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          files: |
            dist/*