on:
  push:
    tags:
      - 'v*'

name: CLI and Manifests Release

jobs:
  release:
    name: Build and publish konfig binary
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.16
        id: go

      - name: Install upx
        run: sudo apt-get install -y upx

      - name: Get Version
        shell: bash
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF##*/})
        id: version

      - name: Build CLI Release
        run: |
          make LDFLAGS="-s -w -X github.com/pelotech/jsonnet-controller/pkg/cmd.Version=${{ steps.version.outputs.tag }}" dist-konfig
          cd dist && sha256sum * > konfig.sha256sum

      - name: Generate Release Manifests
        run: |
          mkdir -p config/release
          VERSION=${{ steps.version.outputs.tag }} BUNDLE_OUTPUT=config/release/jsonnet-controller.yaml make bundle

      - name: Publish Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          files: |
            dist/*
            config/release/jsonnet-controller.yaml