on:
  push:
    tags:
      - 'v*'

name: Konfig Release and Manifests

jobs:
  release:
    name: Build and publish konfig binary
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16
        id: go

      - name: Install upx
        run: sudo apt-get install -y upx

      - name: Get Version
        shell: bash
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF##*/})
        id: version

      - name: Build CLI Release
        run: make dist-konfig

      - name: Generate Release Manifests
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p config/release
          VERSION=${{ steps.version.outputs.tag }} BUNDLE_OUTPUT=config/release/jsonnet-controller.yaml make bundle

      - name: Publish Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          files: |
            dist/*
            config/release/jsonnet-controller.yaml