name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

    # Check out code
    - name: Checkout
      uses: actions/checkout@v2

    # Setup go 1.16
    - name: Setup Go 1.16
      uses: actions/setup-go@v3.4.0
      with:
        go-version: '^1.16.5'

    # Set up Go pkg cache
    - name: Cache Go Packages and controller-util Binaries
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          /home/runner/work/jsonnet-controller/jsonnet-controller/testbin
          /home/runner/work/jsonnet-controller/jsonnet-controller/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Run linting
    - name: Run Lint
      run: make lint

    # Run unit tests - this will also ensure code-generation is run
    - name: Run Unit Tests
      run: make test

    # Update documentation
    - name: Force pkg.go.dev to refresh main branch
      run: curl "https://proxy.golang.org/github.com/pelotech/jsonnet-controller/@v/${GITHUB_REF##*/}.info"
      if: ${{ github.ref == 'refs/heads/main' }}

    - name: Force pkg.go.dev to refresh latest tag
      run: curl https://proxy.golang.org/github.com/pelotech/jsonnet-controller/@v/${{ steps.version.outputs.tag }}.info
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}